name: CI/CD Frontend
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
